version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: pg
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: products_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6380:6379"

volumes:
  pgdata:
